# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

def shared_pods
    pod 'SWRevealViewController', '~> 2.3'
    pod 'MBProgressHUD', '~> 1.0'
    pod 'SDWebImage', '~> 4.0'
    pod 'Alamofire', '~> 4.5'
    pod 'ActionSheetPicker-3.0', '~> 2.2'
end

target 'mTV' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!

    # Pods for mTV
    shared_pods
end

# RxTests and RxBlocking make the most sense in the context of unit/integration tests
target 'mTVTests' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    
    # Pods for mTVTests
    shared_pods
end
